spring.application.name=tvmaze-middleware-api
#Se deja hardcodeado el usuario y contrasenia de la base de datos por practicidad
#Se debe usar variables de entorno para no exponer la informacion sensible en el repositorio
#spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.uri=mongodb+srv://alexismolinero123_db_user:QzCM8hIQWEQtHcho@cluster0.rcf3o0h.mongodb.net/tvmaze?appName=Cluster0
spring.data.mongodb.auto-index-creation=true
