spring.application.name=tvmaze-middleware-api
#Se deja harcodeado el usuario y contraseña de la base de datos por practicidad
#Se debe usar variables de entorno para no exponer la información sensible en el repositorio
#spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.uri=mongodb+srv://dunojij6466_db_user:U0gnomoUUuab7XgS@cluster0.wiglcry.mongodb.net/?appName=Cluster0
